### PR TITLE
Increase rfc compliance

### PR DESCRIPTION
**Pull request by skroczek**
Currently this beautiful library converts every domain with every length into it's punycode representation. But in RFC1034 and RFC2181 is defined that every label (or part) must be between 1 and 63 octets and a full domain name is limited to 255 octets (including the separators).
The idn_to_ascii functions returns an empty string if the given domain is invalid without trigger any error, but I don't think this is the best behaviour.
So I decided to make a pull request, to throw exceptions if an invalid domain is given.

### CODE REVIEW

**Comment by patrick-radius** [comment]
Thanks for your contribution.  I am not a big fan of the assignments in conditions, would it be too much to ask to clean that up a bit?

**Comment by skroczek** [comment]
@patrick-radius Thanks for your feedback. I've fixed it in the last commit. :)

**Comment by ceeram** [comment]
👍 LGTM, thanks!

**Comment by ceeram** [comment]
Created a new release including this change, v2.1.0 Thanks again

**Pull request merged**
